name: tunas_honda_absensi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # auto_route: 0.6.7
  # auto_route_generator: ^0.6.8
  build_runner: null
  cupertino_icons: ^0.1.3
  dartz: ^0.8.9
  data_connection_checker: ^0.3.4
  equatable: ^1.1.1
  # firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.4+3
  flushbar: ^1.10.4
  flutter_bloc: ^3.2.0
  flutter_hooks: ^0.8.0
  freezed: ^0.10.4
  freezed_annotation: ^0.7.1
  geocoder: ^0.2.1
  # geolocator: ^5.3.0
  geolocator: ^6.2.0
  # geolocator: ^7.0.1
  # location_permissions: ^3.0.0+1
  get_it: ^4.0.1
  get_version: ^0.2.2
  google_fonts: ^1.1.0
  google_sign_in: ^4.2.0
  http: ^0.12.0+4
  injectable: ^0.3.0
  injectable_generator: ^0.3.3
  intl: ^0.16.1
  json_serializable: ^3.2.5
  kt_dart: ^0.7.0+1
  lint: ^1.1.1
  lottie: ^0.6.0
  mockito: ^3.0.0
  path: ^1.6.4
  path_provider: ^1.6.11
  progress_dialog: ^1.2.4
  provider: ^4.0.1
  shared_preferences: ^0.5.6+3
  trust_location: ^2.0.11
  uuid: ^2.0.4
  shimmer: ^1.1.1
  js: ^0.6.0
  mapbox_search: ^2.0.1+1
  mapbox_geocoding: ^0.1.3  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  